import { z } from 'zod';
declare const ConfigSchema: z.ZodObject<{
    databaseUrl: z.ZodString;
    alpacaApiKey: z.ZodString;
    alpacaApiSecret: z.ZodString;
    alpacaBaseUrl: z.ZodString;
    openaiApiKey: z.ZodString;
    tradingSymbol: z.ZodDefault<z.ZodString>;
    tradingSymbols: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    allocatedCapital: z.ZodDefault<z.ZodNumber>;
    positionSizePct: z.ZodDefault<z.ZodNumber>;
    maxDrawdownPct: z.ZodDefault<z.ZodNumber>;
    llmModel: z.ZodDefault<z.ZodString>;
    llmTemperature: z.ZodDefault<z.ZodNumber>;
    cronSchedule: z.ZodDefault<z.ZodString>;
    mode: z.ZodDefault<z.ZodEnum<["mock", "paper"]>>;
    engineVersion: z.ZodDefault<z.ZodEnum<["v1", "v2"]>>;
}, "strip", z.ZodTypeAny, {
    engineVersion: "v1" | "v2";
    allocatedCapital: number;
    databaseUrl: string;
    alpacaApiKey: string;
    alpacaApiSecret: string;
    alpacaBaseUrl: string;
    openaiApiKey: string;
    tradingSymbol: string;
    tradingSymbols: string[];
    positionSizePct: number;
    maxDrawdownPct: number;
    llmModel: string;
    llmTemperature: number;
    cronSchedule: string;
    mode: "mock" | "paper";
}, {
    databaseUrl: string;
    alpacaApiKey: string;
    alpacaApiSecret: string;
    alpacaBaseUrl: string;
    openaiApiKey: string;
    engineVersion?: "v1" | "v2" | undefined;
    allocatedCapital?: number | undefined;
    tradingSymbol?: string | undefined;
    tradingSymbols?: string[] | undefined;
    positionSizePct?: number | undefined;
    maxDrawdownPct?: number | undefined;
    llmModel?: string | undefined;
    llmTemperature?: number | undefined;
    cronSchedule?: string | undefined;
    mode?: "mock" | "paper" | undefined;
}>;
export type Config = z.infer<typeof ConfigSchema>;
export declare function loadConfig(): Config;
export declare function getConfig(): Config;
export declare function resetConfig(): void;
export {};
//# sourceMappingURL=config.d.ts.map